# Generated by Django 3.0.3 on 2020-02-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200225_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='Фильм'),
        ),
    ]
