# Generated by Django 3.0.3 on 2020-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200225_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hui_post', models.CharField(max_length=120)),
            ],
        ),
    ]
