# Generated by Django 3.0.3 on 2020-02-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_hui'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hui',
        ),
    ]
