# Generated by Django 3.0.3 on 2020-02-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200226_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Session', verbose_name='На какой фильм?'),
        ),
    ]
