# Generated by Django 3.0.3 on 2020-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200226_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='places',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
